home:
  path: /
  controller: App\Controller\HomeController::index
weapons.index:
  path: /armes
  controller: App\Controller\WeaponsController::index



#index:
#    path: /
#    controller: App\Controller\DefaultController::index
