home:
  path: /
  controller: App\Controller\HomeController::index
weapons.index:
  path: /armes
  controller: App\Controller\WeaponsController::index
logout:
  path: /logout


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
